<?php

namespace tests\app\Libraries;

use app\Libraries\Survey;

class SurveyTest extends \TestCase{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function test_validate_error_when_field_is_required(){
        $Survey = new Survey();
        $Survey->validate();
        $this->assertEquals(array (
            1 =>
                array (
                    0 => 'The total field is required.',
                    1 => 'The percentage field is required.',
                ),
            2 =>
                array (
                    0 => 'The jumlah field is required.',
                ),
            3 =>
                array (
                    0 => 'The dipa.dana pemerintah field is required.',
                    1 => 'The dipa. p n b p field is required.',
                    2 => 'The dipa. p h l n field is required.',
                    3 => 'The dana lainnya.perusahaan swasta field is required.',
                    4 => 'The dana lainnya.instansi pemerintah field is required.',
                    5 => 'The dana lainnya.swasta non profit field is required.',
                    6 => 'The dana lainnya.luar negeri field is required.',
                ),
        ), $Survey->getErrors());
    }

}